import type { LiveGameData } from './types';

/**
 * Sample live game data for the demo/preview pages.
 * Uses real champion names and item IDs so icons resolve from Data Dragon.
 */

const sampleLiveGame: LiveGameData = {
  gameTime: 1247, // ~20:47
  gameMode: 'CLASSIC',
  activePlayer: {
    summonerName: 'You',
    level: 13,
    currentGold: 1420,
    stats: {
      attackDamage: 284,
      abilityPower: 0,
      armor: 98,
      magicResist: 52,
      attackSpeed: 1.14,
      critChance: 0.6,
      critDamage: 1.75,
      moveSpeed: 350,
      maxHealth: 1940,
      currentHealth: 1740,
      resourceMax: 320,
      resourceValue: 210,
      resourceType: 'MANA',
      abilityHaste: 20,
      lifeSteal: 0.15,
      omnivamp: 0,
      physicalLethality: 0,
      magicLethality: 0,
      armorPenetrationFlat: 0,
      armorPenetrationPercent: 0,
      magicPenetrationFlat: 0,
      magicPenetrationPercent: 0,
      tenacity: 0,
      healShieldPower: 0,
      attackRange: 550,
      healthRegenRate: 8.2,
      resourceRegenRate: 7.4,
    },
  },
  players: [
    // ── Blue team (ORDER) ──
    {
      summonerName: 'TopDiff99',
      championName: 'Darius',
      team: 'ORDER',
      position: 'TOP',
      level: 12,
      kills: 4,
      deaths: 3,
      assists: 2,
      creepScore: 168,
      wardScore: 12,
      items: [
        { itemID: 6632, displayName: 'Divine Sunderer', count: 1, slot: 0, price: 3300 },
        { itemID: 3047, displayName: "Plated Steelcaps", count: 1, slot: 1, price: 1100 },
        { itemID: 3053, displayName: "Sterak's Gage", count: 1, slot: 2, price: 3100 },
        { itemID: 3067, displayName: 'Kindlegem', count: 1, slot: 3, price: 800 },
      ],
      skinID: 0,
      isActivePlayer: false,
      isDead: false,
      respawnTimer: 0,
    },
    {
      summonerName: 'JGKing',
      championName: 'LeeSin',
      team: 'ORDER',
      position: 'JUNGLE',
      level: 11,
      kills: 5,
      deaths: 2,
      assists: 8,
      creepScore: 124,
      wardScore: 22,
      items: [
        { itemID: 6693, displayName: 'Prowler\'s Claw', count: 1, slot: 0, price: 3100 },
        { itemID: 3158, displayName: 'Ionian Boots of Lucidity', count: 1, slot: 1, price: 950 },
        { itemID: 3134, displayName: 'Serrated Dirk', count: 1, slot: 2, price: 1100 },
      ],
      skinID: 0,
      isActivePlayer: false,
      isDead: false,
      respawnTimer: 0,
    },
    {
      summonerName: 'You',
      championName: 'Jinx',
      team: 'ORDER',
      position: 'BOTTOM',
      level: 13,
      kills: 8,
      deaths: 1,
      assists: 5,
      creepScore: 192,
      wardScore: 16,
      items: [
        { itemID: 3031, displayName: 'Infinity Edge', count: 1, slot: 0, price: 3400 },
        { itemID: 3006, displayName: "Berserker's Greaves", count: 1, slot: 1, price: 1100 },
        { itemID: 3085, displayName: 'Runaan\'s Hurricane', count: 1, slot: 2, price: 2600 },
        { itemID: 6672, displayName: 'Kraken Slayer', count: 1, slot: 3, price: 3400 },
        { itemID: 1055, displayName: "Doran's Blade", count: 1, slot: 4, price: 450 },
      ],
      skinID: 0,
      isActivePlayer: true,
      isDead: false,
      respawnTimer: 0,
    },
    {
      summonerName: 'SuppGap',
      championName: 'Thresh',
      team: 'ORDER',
      position: 'UTILITY',
      level: 10,
      kills: 1,
      deaths: 4,
      assists: 14,
      creepScore: 32,
      wardScore: 48,
      items: [
        { itemID: 3190, displayName: 'Locket of the Iron Solari', count: 1, slot: 0, price: 2500 },
        { itemID: 3009, displayName: 'Boots of Swiftness', count: 1, slot: 1, price: 900 },
        { itemID: 3109, displayName: "Knight's Vow", count: 1, slot: 2, price: 2300 },
      ],
      skinID: 0,
      isActivePlayer: false,
      isDead: false,
      respawnTimer: 0,
    },
    {
      summonerName: 'MidOrFeed',
      championName: 'Ahri',
      team: 'ORDER',
      position: 'MIDDLE',
      level: 12,
      kills: 6,
      deaths: 2,
      assists: 4,
      creepScore: 178,
      wardScore: 14,
      items: [
        { itemID: 6655, displayName: 'Luden\'s Tempest', count: 1, slot: 0, price: 3200 },
        { itemID: 3020, displayName: "Sorcerer's Shoes", count: 1, slot: 1, price: 1100 },
        { itemID: 3089, displayName: "Rabadon's Deathcap", count: 1, slot: 2, price: 3600 },
        { itemID: 3916, displayName: 'Oblivion Orb', count: 1, slot: 3, price: 800 },
      ],
      skinID: 0,
      isActivePlayer: false,
      isDead: false,
      respawnTimer: 0,
    },
    // ── Red team (CHAOS) ──
    {
      summonerName: 'xXSlayerXx',
      championName: 'Yone',
      team: 'CHAOS',
      position: 'TOP',
      level: 13,
      kills: 7,
      deaths: 3,
      assists: 3,
      creepScore: 186,
      wardScore: 8,
      items: [
        { itemID: 3153, displayName: "Blade of the Ruined King", count: 1, slot: 0, price: 3200 },
        { itemID: 3006, displayName: "Berserker's Greaves", count: 1, slot: 1, price: 1100 },
        { itemID: 6672, displayName: 'Kraken Slayer', count: 1, slot: 2, price: 3400 },
        { itemID: 3086, displayName: 'Zeal', count: 1, slot: 3, price: 1050 },
      ],
      skinID: 0,
      isActivePlayer: false,
      isDead: false,
      respawnTimer: 0,
    },
    {
      summonerName: 'ForestGuard',
      championName: 'Vi',
      team: 'CHAOS',
      position: 'JUNGLE',
      level: 11,
      kills: 3,
      deaths: 5,
      assists: 6,
      creepScore: 118,
      wardScore: 18,
      items: [
        { itemID: 6631, displayName: 'Stridebreaker', count: 1, slot: 0, price: 3300 },
        { itemID: 3047, displayName: "Plated Steelcaps", count: 1, slot: 1, price: 1100 },
        { itemID: 3044, displayName: 'Phage', count: 1, slot: 2, price: 1100 },
      ],
      skinID: 0,
      isActivePlayer: false,
      isDead: true,
      respawnTimer: 18,
    },
    {
      summonerName: 'ZedMain420',
      championName: 'Zed',
      team: 'CHAOS',
      position: 'MIDDLE',
      level: 12,
      kills: 5,
      deaths: 4,
      assists: 2,
      creepScore: 164,
      wardScore: 6,
      items: [
        { itemID: 6693, displayName: 'Prowler\'s Claw', count: 1, slot: 0, price: 3100 },
        { itemID: 3158, displayName: 'Ionian Boots of Lucidity', count: 1, slot: 1, price: 950 },
        { itemID: 3071, displayName: 'Black Cleaver', count: 1, slot: 2, price: 3100 },
      ],
      skinID: 0,
      isActivePlayer: false,
      isDead: false,
      respawnTimer: 0,
    },
    {
      summonerName: 'ADC Diff',
      championName: 'Caitlyn',
      team: 'CHAOS',
      position: 'BOTTOM',
      level: 12,
      kills: 3,
      deaths: 5,
      assists: 4,
      creepScore: 170,
      wardScore: 10,
      items: [
        { itemID: 3031, displayName: 'Infinity Edge', count: 1, slot: 0, price: 3400 },
        { itemID: 3006, displayName: "Berserker's Greaves", count: 1, slot: 1, price: 1100 },
        { itemID: 3094, displayName: 'Rapid Firecannon', count: 1, slot: 2, price: 2500 },
      ],
      skinID: 0,
      isActivePlayer: false,
      isDead: false,
      respawnTimer: 0,
    },
    {
      summonerName: 'WardBot',
      championName: 'Leona',
      team: 'CHAOS',
      position: 'UTILITY',
      level: 9,
      kills: 0,
      deaths: 7,
      assists: 10,
      creepScore: 24,
      wardScore: 42,
      items: [
        { itemID: 3190, displayName: 'Locket of the Iron Solari', count: 1, slot: 0, price: 2500 },
        { itemID: 3047, displayName: "Plated Steelcaps", count: 1, slot: 1, price: 1100 },
        { itemID: 3024, displayName: 'Glacial Buckler', count: 1, slot: 2, price: 900 },
      ],
      skinID: 0,
      isActivePlayer: false,
      isDead: true,
      respawnTimer: 22,
    },
  ],
  killFeed: [
    { eventTime: 185, killerName: 'JGKing', victimName: 'ForestGuard', assisters: ['Darius'], killerChamp: 'LeeSin', victimChamp: 'Vi' },
    { eventTime: 243, killerName: 'xXSlayerXx', victimName: 'MidOrFeed', assisters: [], killerChamp: 'Yone', victimChamp: 'Ahri' },
    { eventTime: 310, killerName: 'You', victimName: 'ADC Diff', assisters: ['Thresh'], killerChamp: 'Jinx', victimChamp: 'Caitlyn' },
    { eventTime: 412, killerName: 'ZedMain420', victimName: 'MidOrFeed', assisters: [], killerChamp: 'Zed', victimChamp: 'Ahri' },
    { eventTime: 498, killerName: 'You', victimName: 'WardBot', assisters: ['Thresh', 'LeeSin'], killerChamp: 'Jinx', victimChamp: 'Leona' },
    { eventTime: 560, killerName: 'TopDiff99', victimName: 'xXSlayerXx', assisters: ['LeeSin'], killerChamp: 'Darius', victimChamp: 'Yone' },
    { eventTime: 623, killerName: 'xXSlayerXx', victimName: 'TopDiff99', assisters: ['Vi'], killerChamp: 'Yone', victimChamp: 'Darius' },
    { eventTime: 710, killerName: 'You', victimName: 'ZedMain420', assisters: [], killerChamp: 'Jinx', victimChamp: 'Zed' },
    { eventTime: 784, killerName: 'MidOrFeed', victimName: 'ForestGuard', assisters: ['Jinx'], killerChamp: 'Ahri', victimChamp: 'Vi' },
    { eventTime: 856, killerName: 'ADC Diff', victimName: 'SuppGap', assisters: ['Leona'], killerChamp: 'Caitlyn', victimChamp: 'Thresh' },
    { eventTime: 920, killerName: 'You', victimName: 'xXSlayerXx', assisters: ['Darius', 'Thresh'], killerChamp: 'Jinx', victimChamp: 'Yone' },
    { eventTime: 1005, killerName: 'xXSlayerXx', victimName: 'SuppGap', assisters: [], killerChamp: 'Yone', victimChamp: 'Thresh' },
    { eventTime: 1087, killerName: 'You', victimName: 'ADC Diff', assisters: ['Ahri'], killerChamp: 'Jinx', victimChamp: 'Caitlyn' },
    { eventTime: 1150, killerName: 'JGKing', victimName: 'WardBot', assisters: [], killerChamp: 'LeeSin', victimChamp: 'Leona' },
    { eventTime: 1210, killerName: 'You', victimName: 'ZedMain420', assisters: ['Thresh'], killerChamp: 'Jinx', victimChamp: 'Zed' },
  ],
};

/** Sample data for the live game demo page */
export const sampleLiveGameData: LiveGameData = sampleLiveGame;

/** Sample data for the post-game demo page (same game, with a Win result) */
export const samplePostGameData: LiveGameData = {
  ...sampleLiveGame,
  gameTime: 1680, // 28:00
  gameResult: 'Win',
  players: sampleLiveGame.players.map((p) => {
    // Bump kills / CS a bit for the final snapshot
    if (p.team === 'ORDER') {
      return { ...p, kills: p.kills + 2, creepScore: p.creepScore + 30 };
    }
    // Give Yone a big late-game pop-off so he's the game MVP (enemy carry scenario)
    if (p.championName === 'Yone') {
      return { ...p, kills: 14, deaths: 4, assists: 6, creepScore: p.creepScore + 40 };
    }
    return { ...p, deaths: p.deaths + 1, creepScore: p.creepScore + 20 };
  }),
};
